### ISSUE TITLE
implement server side compilation for angular 2

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#143]
When a user log in to the system for the 1st time. It takes a long time to render the page. a reason might be that angular 2 compiles the template on client side before rendering it. Please implement server side compilation to improve speed.

**Comment by ankit213** [comment]
Started Date :  04-11-2016
Estimated Time : 16 Hours
End Date: 07-11-2016

**Comment by ankit213** [comment]
I have used Ahead-of-time (AOT) for solving the above issue but there is a problem in Md2, md2@0.0.6 fails with angular-CLI AOT compiler [https://github.com/Promact/md2/issues/28], so present I am stuck on this issue.

**Comment by ankit213** [comment]
I have worked on AHEAD-OF-TIME COMPILATION, After compilation AOT folder is generated successful, but an issue in app.modulengfactory.ts file, it throws error like Build: Generic type 'HttpService' requires 1 type argument(s). When I build Project. I have posted an issue on [http://stackoverflow.com/questions/41157578/ahead-of-time-compilation-issue](Link)

**Comment by iamronakshah** [comment]
@ankit was removed Http Service in entire project but now its throws error on build like Build: property 'requried' does not exist on type '{[key : string]:any;}'  in *.modulengfactory.ts file.

**Comment by chintans** [comment]
What is the status on this?

**Comment by ankit213** [comment]
@iamronakshah worked on this but right now it is having a road block

**Comment by chintans** [comment]
What is the roadblock?

**Comment by ankit213** [comment]
he is posted on this [link](http://stackoverflow.com/questions/42618284/ahead-of-time-compilation-issues)

**Comment by siddharthashw** [comment]
Need to do analysis for it.... Started with AOT [dcocument](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)

**Comment by siddharthashw** [comment]
Start Date : 03/04/2017
Estimated Time : 4 hours
End Date: 03/04/2017

**Comment by chintans** [comment]
Does 4 hours include analysis too?

**Comment by siddharthashw** [comment]
No, 4 hour to implement, created gulp.task and testing

**Comment by chintans** [comment]
Please add your analysis time too

**Comment by siddharthashw** [comment]
1) Analysis - 4 hours, as because on AOT [doc](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#inspect-bundle), they have used for angular 4.0.0
2) Implement for AOT - 2 hours 30 minutes
3) Gulp.task and testing - 1 hour 30 minutes

**Comment by chintans** [comment]
Is this issue completed? I just checked latest version and it does not have AOT implemented.

**Comment by siddharthashw** [comment]
Actually it was not working right now. That why kept it out for now.

I am working on it. Issue - #332
