### ISSUE TITLE
Remember My Choice does not work

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#261]
When ever I click on login with Promact It shows me page where I need to grant permission. It should only show that screen once. Because once I have autorized an application I don't need to re-authorize it every time I login. Similar behavior can be seen in Login With Facebook where you authorize an app only once next time onward it will not show you same screen..

**Comment by siddharthashw** [comment]
There is a field in IdentityServer Client that is RequiredConstent..... If it set to true then for scope-offline_access for every request you need to allow the constent. Else if you set the constent to false then it will not ask for permission every.

Now you suggest the way.

**Comment by siddharthashw** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/928

Please refer the above link...

Either we can remove the scope of offline_access (for refresh token) or we can turn this consent page off

**Comment by chintans** [comment]
After reading the entire thread. They do have a different solution. Have you gone through this solution?

> Your easiest approach for this now is to replace (or derive from) our default consent service: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs
and then copy the code from RequiresConsent: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs#L50
but leave out the check for offline access: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs#L72

**Comment by siddharthashw** [comment]
This solution has been provide by them 10 day ago. yet I don't know, will it work. 

And this is there source code. 
So want me to override their source code.

**Comment by chintans** [comment]
> This solution has been provide by them 10 day ago. yet I don't know, will it work.

Solution is 10 days old but your comment is on today. When you were asked to fix issue. You commented here without confirming that there is a solution.

>And this is there source code.
So want me to override their source code.

I am not sure what you are asking but the author has clearly given solution in his statements.

**Comment by siddharthashw** [comment]
Start Date : 30/03/2017
Estimated time : 1 hours
End Date : 30/03/2017
