### ISSUE TITLE
implement an API to fetch user details along with projects

### ISSUE THREAD

**Issue by Krunal-Promact** [Promact/oauth-server#297]
- In TestCase Mangement I want to fetch user details along with projects in which he/she is either team leader or team member.
- In request, user id will be passed to API and in response, API should return user details along with the projects associated with it plus user's role in each project(either Team Leader or Team Member)

**Comment by siddharthashw** [comment]
While working on ERP - issue 241, @juliepromact found that she have same requirement as the above, so will be working for it. I have discussed with @ankit213 for the issue.
