### ISSUE TITLE
Project list page  display blank grid

### ISSUE THREAD

**Issue by ankit213** [Promact/oauth-server#318]
**I'm submitting a ...**  (check one with "x")

[x] bug report => project list page not disaply message            
[ ] feature request => 

**Step/s to reproduce issue**
1. login with user and click on project option
2. It displays blank grid, It should display "No record to display" if there is no record.

**Screen shot**
![image](https://cloud.githubusercontent.com/assets/9895825/24188252/a09d8cb4-0f06-11e7-938d-25ef5edfa6b4.png)

**Comment by iamronakshah** [comment]
Start Date - 22/03/2017
Estimated time - 45 mins
End Date - 22/03/2017
