### ISSUE TITLE
Design Reset Password Confirmation Page

### ISSUE THREAD

**Issue by ankit213** [Promact/oauth-server#322]
**I'm submitting a ...**  (check one with "x")

[x] support report => design reset password confirmation page                
[ ] feature request => 

**Step/s to reproduce issue**
**1.** Click on forgot password link and give the email address 
**2.** Open email and click on reset password link 
**3.** After successfully reset password it will redirect to reset password confirmation page.                   

**Screen shot**
![pasted image at 2017_03_22 03_34 pm](https://cloud.githubusercontent.com/assets/9895825/24193016/d0e2e382-0f16-11e7-8a89-324ab1015e50.png)

**Comment by Asrapromact** [comment]
Start date: 22-03-2017
End date: 22-03-2017
Estimaiton time : 1.5 hours
