### ISSUE TITLE
Upgrade project to VS2017

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#325]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting.                          
- [x] feature request => 

**Step/s to reproduce issue**
Upgrade project from xproj to csproj to support upgrading to latest version of DotNet core

**Screen shot**

**Comment by juliepromact** [comment]
Start Date - 10-04-2017
End Date - 10-04-2017
Estimated Time - 30 min

**Comment by chintans** [comment]
This will change Docker file as currently docker is using old xproj to build. make sure to update Dockerfile too.
