### ISSUE TITLE
Upgrade IdentityServer to latest version (1.4)

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#326]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting.                          
- [X] feature request => 

**Step/s to reproduce issue**
Upgrade IdentityServer dependency to latest version of 1.4. Check here for release notes
https://github.com/IdentityServer/IdentityServer4/releases

**Screen shot**

**Comment by siddharthashw** [comment]
@chintans , You want me to update IdentityServer dependency to latest version or 1.4.

Because latest version, now is 1.5 and you have mention 1.4

**Comment by chintans** [comment]
When I created issue it was the latest. Now 1.5 just came yesterday, So, Please upgrade it to 1.5
