### ISSUE TITLE
Upgrade Angular 2 to it's latest version

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#327]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting.                          
- [X] feature request => 

**Step/s to reproduce issue**
Upgrade Angular to 2.4.10 version

**Screen shot**

**Comment by ankit213** [comment]
@chintans : can I upgrade Angular 4.0 version instead 2.4.10 ?

**Comment by chintans** [comment]
If it is compatible than yes

**Comment by ankit213** [comment]
Start Date : 07-04-2017
Estimaiton Time : 14 Hours (Included Client Side Test Cases)
End Date : 10-04-2017

**Comment by Asrapromact** [comment]
Start date : 12-04-2017
End date : 12-04-2017
Estimation time : 5.5 hours
