### ISSUE TITLE
Upgrade all other client and server dependencies in project

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#328]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting.                          
- [X] feature request => 

**Step/s to reproduce issue**
Upgrade all dependencies in project

**Screen shot**

**Comment by ankit213** [comment]
Start Date For Upgrade all another client side : 10-04-2017
Estimation Time : 2 Hours
End Date : 10-04-2017

**Comment by juliepromact** [comment]
Start Date For Upgrade all server side : 12-04-2017
Estimation Time : 1 Hour
End Date : 12-04-2017
