### ISSUE TITLE
AOT Restriction should be updated , After angular version 4.0.0

### ISSUE THREAD

**Issue by ankit213** [Promact/oauth-server#332]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting.                          
[x] feature request =>

**Comment by siddharthashw** [comment]
As there are some **"DON'T"** sets of Rules in AOT, which was not occurring on previous version of angular - #327 .
but after updating it to latest, AOT rules are now generating obstacle in my path to build the solution.
Here is the issue 

`Property 'required' does not exist on type '{ [key: string]: any; }` 

After some analysis I found this below rules : -
**AOT Don'ts**

The following are some things that will make AOT compile fail.

Don’t use require statements for your templates or styles, use styleUrls and templateUrls, the angular2-template-loader plugin will change it to require at build time.
Don’t use default exports.
Don’t use form.controls.controlName, use form.get(‘controlName’)
Don’t use control.errors?.someError, use control.hasError(‘someError’)
Don’t use functions in your providers, routes or declarations, export a function and then reference that function name
Inputs, Outputs, View or Content Child(ren), Hostbindings, and any field you use from the template or annotate for Angular should be public

And now to resolve this I have to use reactive form.

**Comment by siddharthashw** [comment]
Start Date : 12/04/2017
Estimated time : 8 hours
End Date : 17/04/2017
Hours distribution - 2 hours per day

**Comment by siddharthashw** [comment]
Same issue link and suggestion - 

https://github.com/angular/angular/issues/12181
https://github.com/qdouble/angular-webpack2-starter#aot--donts
http://stackoverflow.com/questions/39881367/property-does-not-exist-on-type-key-string-abstractcontrol

**Comment by siddharthashw** [comment]
To meet the above requirement, I have updated the angular version to 4.0.0 and updated aot to its latest and updated the client side test case

Start Date : 13/04/2017
Estimated time : 12 hours
End Date : 15/04/2017

Hour distributions : -
1. 4 hour on 13/04/2017
2. 4 hours on 14/04/2017 
3. 4 hours on 15/04/2017
