### ISSUE TITLE
Status checkbox not required while Adding project

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#333]
**I'm submitting a ...**  (check one with "x")

- [X] bug report => search github for a similar issue or PR before submitting.                          
[ ] feature request => 

**Step/s to reproduce issue**
Login as Admin
Go to Add Project                       

**Screen shot**

![statusissuewhileaddingnewproject](https://cloud.githubusercontent.com/assets/5684450/24946120/6837b65e-1f7f-11e7-9144-f0d3a1f3f674.PNG)

There is no point of providing status while adding new project. There should be a button in update project to disable a project.

**Comment by juliepromact** [comment]
Start date - 12-04-2017
Estimated time - 1 hour
End Date - 12-04-2017
