### ISSUE TITLE
No label for Joining date field

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#334]
**I'm submitting a ...**  (check one with "x")

- [X] bug report => search github for a similar issue or PR before submitting.                          
[ ] feature request => 

**Step/s to reproduce issue**
Log in as Admin
Add User

**Screen shot**

![nolabel](https://cloud.githubusercontent.com/assets/5684450/24946287/1863a25e-1f80-11e7-89c0-e938dd9c3375.PNG)

There is no label that tells user what this field is for. Please add appropriate label or placeholder

**Comment by ankit213** [comment]
Issue is done but right now not reflect in live
