### ISSUE TITLE
Dependency warnings

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#349]
warning "@angular/core@4.0.0" has incorrect peer dependency "rxjs@^5.0.1".
warning "@angular/http@4.0.0" has incorrect peer dependency "rxjs@^5.0.1".
warning "angular2-in-memory-web-api@0.0.21" has incorrect peer dependency "@angular/core@^2.0.0".
warning "angular2-in-memory-web-api@0.0.21" has incorrect peer dependency "@angular/http@^2.0.0".
warning "angular2-in-memory-web-api@0.0.21" has incorrect peer dependency "zone.js@^0.6.25".
warning "@angular/router@3.1.2" has incorrect peer dependency "@angular/core@2.1.2".
warning "@angular/router@3.1.2" has incorrect peer dependency "@angular/common@2.1.2".
warning "@angular/router@3.1.2" has incorrect peer dependency "@angular/platform-browser@2.1.2".

Please fix these warnings

**Comment by siddharthashw** [comment]
Start Date : 24/04/2017
Estimated time : 3 hours
End Date : 24/04/2017
